name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest 
    name: Detect Changed Paths
    outputs:
      changed-paths: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with:
          separator: ','
          files_ignore: |
            .github
            README.md

      - name: List all changed files
        run: |
          echo "[ ${{ steps.changed-files.outputs.all_changed_files }} ]"