name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest 
    name: Detect Changed Paths
    outputs:
      changed-paths: ${{ steps.array.outputs.build }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with:
          separator: ", "
          files: |
            **/Dockerfile

      - uses: kanga333/json-array-builder@v0.1.0
        id: array
        with:
          separator: ","
          str: ${{ steps.changed-files.outputs.all_changed_files }}

  build:
    runs-on: ubuntu-latest
    needs: [changes]
    name: Detect Changed Paths
    strategy:
      matrix:
        changed-paths: ${{ fromJson(needs.changes.outputs.changed-paths) }}
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: jonyjalfon94/workflow-templates
          token: ${{ secrets.TOKEN }}
          path: .github

      - name: Set image and tag
        id: set-vars
        env:
          DOCKERFILE_PATH: ${{ matrix.changed-paths }}
        run: |
          PATH_WITHOUT_DOCKERFILE=${DOCKERFILE_PATH%*/Dockerfile}
          echo "::set-output name=context::${PATH_WITHOUT_DOCKERFILE}"
          echo "::set-output name=image::${PATH_WITHOUT_DOCKERFILE%/*}"
          echo "::set-output name=tag::${PATH_WITHOUT_DOCKERFILE#*/}"
      
      - uses: ./.github/actions/build-and-push-docker-2
        name: Build and Push Docker Image
        with:
          push: true
          image_name: ${{ steps.set-vars.outputs.image }}
          tag: ${{ steps.set-vars.outputs.tag }}
          context: ${{ steps.set-vars.outputs.context }}
          docker_username: jonyjalfon94
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_args: |
            SERVICE_COMMIT=${{ github.sha }}
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            SERVICE_VERSION=${{ github.sha }}
            SERVICE_BUILD_TIME=${{ steps.date.outputs.date }}