name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest 
    name: Detect Changed Paths
    outputs:
      changed-paths: ${{ steps.array.outputs.build }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with:
          separator: ", "
          files: |
            **/Dockerfile

      - uses: kanga333/json-array-builder@master
        id: array
        with:
          separator: ","
          str: ${{ steps.changed-files.outputs.all_changed_files }}

  build:
    runs-on: ubuntu-latest
    needs: [changes]
    name: Detect Changed Paths
    strategy:
      matrix:
        changed-paths: ${{ fromJson(needs.changes.outputs.changed-paths) }}

    steps:
      - name: Echo file
        run: echo ${{ matrix.changed-paths }}